#pragma once

namespace Vakol::Rendering
{
    struct VertexCommand;
}

namespace Vakol::Rendering::OpenGL
{
    /**
     * \brief Generate a vertex array object within an OpenGL context
     * \param vertexData the pointer to the vertex data.
     * \param indexData the pointer to the indices data.
     * \param command the vertex command to be modified by the function.
     */
    void GenerateVertexArray(const void* vertexData, const void* indexData, VertexCommand& command);
    /**
     * \brief Generate a vertex array object for a skybox within an OpenGL context.
     * \param vertexData the pointer to the vertex data.
     * \param command the vertex command to be modified by the function.
     */
    void GenerateSkyboxVertexArray(const void* vertexData, VertexCommand& command);

    /**
     * \brief binds a vertex array object within an OpenGL context
     * \param vertexArray the unique vertex array id generated by OpenGL
     */
    void BindVertexArray(unsigned int vertexArray);

    /**
     * \brief unbinds a vertex array object within an OpenGL context.
     */
    void UnbindVertexArray();
} // namespace Vakol::Rendering::OpenGL