#pragma once

#include <string>

namespace Vakol::Rendering
{
    struct VertexCommand
    {
        int nVertices = 0; // the number of vertices
        int nIndices = 0;  // the number of indices.

        unsigned int vertexArray = 0u;  // the id of a vertex array generated by the third-party rendering API
        unsigned int vertexBuffer = 0u; // // the id of a vertex buffer generated by the third-party rendering API
    };

    [[nodiscard]] std::string GenerateID(); // generate a unique ID in the format of a string
} // namespace Vakol::Rendering
