name: Catch2 Build

on:
  pull_request:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/Core -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSUPPRESS_LOGS=TRUE

      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --target VakolTests --config ${{env.BUILD_TYPE}}

      - name: Run tests
        run: |
          try {
            D:\a\VakolEngine\VakolEngine/build/Release/VakolTests.exe
          } catch {
            Write-Error $_.Exception.Message
          }
